from __future__ import annotations

import os
from typing import Any

import httpx

from app.microsoft_auth import MicrosoftAuthError, MicrosoftAuthService


class OutlookServiceError(Exception):
    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


def format_review_email(review_payload: dict[str, Any]) -> tuple[str, str]:
    repository = review_payload["repository"]
    pull_request = review_payload["pull_request"]
    review = review_payload["review"]
    number = pull_request.get("number", "?")
    title = pull_request.get("title", "Untitled pull request")
    url = pull_request.get("url", "")
    recommendation = review.get("recommendation", "manual_review")
    risk = review.get("risk", "unknown")
    subject = f"PR Review: {repository} #{number} - {recommendation}"
    lines = [
        f"Repository: {repository}",
        f"Pull request: #{number} - {title}",
        f"Risk: {str(risk).upper()}",
        f"Recommendation: {str(recommendation).upper()}",
        "",
        "Summary",
        review.get("summary", "No summary provided."),
        "",
        "Issues",
    ]
    issues = review.get("issues", [])
    if issues:
        for index, issue in enumerate(issues, start=1):
            severity = str(issue.get("severity", "unknown")).upper()
            file_name = issue.get("file")
            location = f" [{file_name}]" if file_name else ""
            lines.extend([
                f"{index}. [{severity}]{location} {issue.get('title', 'Issue')}",
                f"   {issue.get('detail', '')}",
                f"   Recommendation: {issue.get('recommendation', '')}",
            ])
    else:
        lines.append("No material issues identified.")
    lines.extend(["", "Missing tests"])
    missing_tests = review.get("tests_missing", [])
    if missing_tests:
        lines.extend(f"- {item}" for item in missing_tests)
    else:
        lines.append("No missing tests identified.")
    if url:
        lines.extend(["", f"Pull request: {url}"])
    lines.extend(["", "This message was generated by the AI PR Reviewer and saved as a draft for human review."])
    return subject, "\n".join(lines)


class OutlookService:
    def __init__(
        self,
        recipient: str | None = None,
        auth_service: MicrosoftAuthService | None = None,
        client: httpx.Client | None = None,
        base_url: str = "https://graph.microsoft.com/v1.0",
    ) -> None:
        self.recipient = recipient or os.getenv("OUTLOOK_REVIEW_RECIPIENT")
        self.base_url = base_url.rstrip("/")
        if not self.recipient:
            raise OutlookServiceError(503, "Outlook review recipient is not configured")
        try:
            self.auth_service = auth_service or MicrosoftAuthService()
        except MicrosoftAuthError as exc:
            raise OutlookServiceError(exc.status_code, exc.detail) from exc
        self.client = client or httpx.Client(timeout=20.0)
        self._owns_client = client is None

    def close(self) -> None:
        if self._owns_client:
            self.client.close()

    def _access_token(self) -> str:
        try:
            return self.auth_service.get_access_token()
        except MicrosoftAuthError as exc:
            raise OutlookServiceError(exc.status_code, exc.detail) from exc

    def create_review_draft(self, review_payload: dict[str, Any]) -> dict[str, Any]:
        subject, body = format_review_email(review_payload)
        message = {
            "subject": subject,
            "body": {"contentType": "Text", "content": body},
            "toRecipients": [{"emailAddress": {"address": self.recipient}}],
        }
        access_token = self._access_token()
        try:
            response = self.client.post(
                f"{self.base_url}/me/messages",
                headers={"Authorization": f"Bearer {access_token}", "Content-Type": "application/json"},
                json=message,
            )
        except httpx.RequestError as exc:
            raise OutlookServiceError(502, "Unable to reach Microsoft Graph") from exc
        if response.status_code >= 400:
            if response.status_code == 401:
                detail, status_code = "Microsoft Graph authentication failed", 503
            elif response.status_code == 403:
                detail, status_code = "Microsoft Graph Mail.ReadWrite delegated permission is required", 503
            elif response.status_code == 429:
                detail, status_code = "Microsoft Graph rate limit exceeded", 503
            else:
                detail, status_code = "Microsoft Graph draft creation failed", 502
            raise OutlookServiceError(status_code, detail)
        try:
            data = response.json()
            draft_id = data["id"]
            is_draft = data["isDraft"]
            if not draft_id or is_draft is not True:
                raise ValueError("Invalid draft response")
            return {
                "id": draft_id,
                "subject": data.get("subject", subject),
                "is_draft": True,
                "web_link": data.get("webLink"),
                "recipient": self.recipient,
            }
        except (KeyError, TypeError, ValueError) as exc:
            raise OutlookServiceError(502, "Microsoft Graph returned an invalid draft response") from exc
