from __future__ import annotations

import os
from typing import Any

import httpx


class OutlookServiceError(Exception):
    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


def format_review_email(review_payload: dict[str, Any]) -> tuple[str, str]:
    repository = review_payload["repository"]
    pull_request = review_payload["pull_request"]
    review = review_payload["review"]

    number = pull_request.get("number", "?")
    title = pull_request.get("title", "Untitled pull request")
    url = pull_request.get("url", "")
    recommendation = review.get("recommendation", "manual_review")
    risk = review.get("risk", "unknown")

    subject = f"PR Review: {repository} #{number} - {recommendation}"

    lines = [
        f"Repository: {repository}",
        f"Pull request: #{number} - {title}",
        f"Risk: {str(risk).upper()}",
        f"Recommendation: {str(recommendation).upper()}",
        "",
        "Summary",
        review.get("summary", "No summary provided."),
        "",
        "Issues",
    ]

    issues = review.get("issues", [])
    if issues:
        for index, issue in enumerate(issues, start=1):
            severity = str(issue.get("severity", "unknown")).upper()
            file_name = issue.get("file")
            location = f" [{file_name}]" if file_name else ""
            lines.extend(
                [
                    f"{index}. [{severity}]{location} {issue.get('title', 'Issue')}",
                    f"   {issue.get('detail', '')}",
                    f"   Recommendation: {issue.get('recommendation', '')}",
                ]
            )
    else:
        lines.append("No material issues identified.")

    lines.extend(["", "Missing tests"])
    missing_tests = review.get("tests_missing", [])
    if missing_tests:
        lines.extend(f"- {item}" for item in missing_tests)
    else:
        lines.append("No missing tests identified.")

    if url:
        lines.extend(["", f"Pull request: {url}"])

    lines.extend(
        [
            "",
            "This message was generated by the AI PR Reviewer and saved as a draft for human review.",
        ]
    )

    return subject, "\n".join(lines)


class OutlookService:
    def __init__(
        self,
        access_token: str | None = None,
        recipient: str | None = None,
        client: httpx.Client | None = None,
        base_url: str = "https://graph.microsoft.com/v1.0",
    ) -> None:
        self.access_token = access_token or os.getenv("MICROSOFT_GRAPH_ACCESS_TOKEN")
        self.recipient = recipient or os.getenv("OUTLOOK_REVIEW_RECIPIENT")
        self.base_url = base_url.rstrip("/")

        if not self.access_token:
            raise OutlookServiceError(503, "Microsoft Graph access token is not configured")
        if not self.recipient:
            raise OutlookServiceError(503, "Outlook review recipient is not configured")

        self.client = client or httpx.Client(timeout=20.0)
        self._owns_client = client is None

    def close(self) -> None:
        if self._owns_client:
            self.client.close()

    def create_review_draft(self, review_payload: dict[str, Any]) -> dict[str, Any]:
        subject, body = format_review_email(review_payload)
        message = {
            "subject": subject,
            "body": {
                "contentType": "Text",
                "content": body,
            },
            "toRecipients": [
                {
                    "emailAddress": {
                        "address": self.recipient,
                    }
                }
            ],
        }

        try:
            response = self.client.post(
                f"{self.base_url}/me/messages",
                headers={
                    "Authorization": f"Bearer {self.access_token}",
                    "Content-Type": "application/json",
                },
                json=message,
            )
        except httpx.RequestError as exc:
            raise OutlookServiceError(502, "Unable to reach Microsoft Graph") from exc

        if response.status_code >= 400:
            if response.status_code == 401:
                detail = "Microsoft Graph authentication failed"
                status_code = 503
            elif response.status_code == 403:
                detail = "Microsoft Graph Mail.ReadWrite permission is required"
                status_code = 503
            elif response.status_code == 429:
                detail = "Microsoft Graph rate limit exceeded"
                status_code = 503
            else:
                detail = "Microsoft Graph draft creation failed"
                status_code = 502
            raise OutlookServiceError(status_code, detail)

        try:
            data = response.json()
            return {
                "id": data["id"],
                "subject": data.get("subject", subject),
                "is_draft": data.get("isDraft", True),
                "web_link": data.get("webLink"),
                "recipient": self.recipient,
            }
        except (KeyError, TypeError, ValueError) as exc:
            raise OutlookServiceError(502, "Microsoft Graph returned an invalid draft response") from exc
